name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_KEY" | tr -d '\r' > ssh_key.pem
          chmod 600 ssh_key.pem
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

      - name: Copy frontend files to server
        env:
          DROPLET_IP: ${{ secrets.DROPLET_IP }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          scp -i ssh_key.pem -o IdentitiesOnly=yes -r client/dist/* $SSH_USER@$DROPLET_IP:/var/www/hr-microservice-html/

      - name: Deploy and restart services
        env:
          DROPLET_IP: ${{ secrets.DROPLET_IP }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
         sudo ssh -i ssh_key.pem -o IdentitiesOnly=yes $SSH_USER@$DROPLET_IP << 'EOF'
            cd /var/www/hr-microservice
            git pull origin main
            sudo chown -R www-data:www-data /var/www/hr-microservice-html
            pm2 restart hr-backend
            sudo systemctl reload nginx
          EOF

      - name: Cleanup
        run: rm -f ssh_key.pem
